### ISSUE TITLE
Eclipse bullet gains damage when rotating out of slot 5

### ISSUE THREAD

**Issue by Alex-x90** [blueUserRed/forty-five#135]
**Describe the bug**

The description of the Eclipse bullet says that it gains damage when rotating into slot 5, but if either it's protected and you shoot or it's rotated out by the witch enemies who force you to rotate, it still gains the damage.

**Steps to Reproduce**

1. Protect the eclipse bullet before firing
2. Fire the eclipse bullet with a bullet in slot 2

**Expected behavior**

When rotating out of slot 5, the eclipse bullet doesn't gain damage.

**Attachments**

Before shooting:
![image](https://github.com/blueUserRed/forty-five/assets/40383341/13c884db-f877-4eeb-a40a-7962ab512999)
After Shooting:
![image](https://github.com/blueUserRed/forty-five/assets/40383341/e6652223-48a6-469f-bed3-b80fb8ca43e3)
Log: [forty-five.log](https://github.com/blueUserRed/forty-five/files/14895864/forty-five.log)

**Version**

Version: rc240339 (current steam version)

As a side note (in part due to this bug), the eclipse bullet with the BFB feels very strong, might need some tuning.

**Comment by blueUserRed** [comment]
fix is live on steam, closing this issue. Thanks againg for the report!
