### ISSUE TITLE
Parry with shotgun-shell bullet: Damage secondary enemies?

### ISSUE THREAD

**Issue by PhoenixIV** [blueUserRed/forty-five#165]
Using a shotgun-shell bullet to parry only absorbs damage. Would it be viable to let it damage other enemies during parry? Truly just a question - it might be overpowered.

**Comment by blueUserRed** [comment]
Hello, thanks for the suggestion. We don't think this behaviour would be intuitive, as the bullet isn't actually shot, its just used for parrying, the same way on-shot doesn't trigger when using it to parry.
