### ISSUE TITLE
gegner nerfen, weniger schaden und weniger leben, zumindest bei denen in road 1 und bissi weniger durcvhgehend hohe attcks

### ISSUE THREAD

**Issue by YamiVulgaris** [blueUserRed/forty-five#59]
title, ich weiß nicht ob das jetzt schon die zahlen aus dem notion sind tho
der pyro hat nur ein leben,
vllt die gegner zuerst kleine attacks so 6-10er breich und immer nach zwei drei turns einen fetten hit, wo halt auch manchmal was durchgeht, nicht gleich das im ersten zug beide gegner 18 dmg machen

**Comment by blueUserRed** [comment]
addressed by #85
