### ISSUE TITLE
Missing encounter backgrounds

### ISSUE THREAD

**Issue by blueUserRed** [blueUserRed/forty-five#75]
**Description**

Background Textures for the Encounter screen in biomes that are not Wasteland are missing.

**Steps to Reproduce**

- Enter road with the bewitched forest biome.
- Start a fight.

**Version**
dev/b231222

**Comment by blueUserRed** [comment]
The missing textures are not uploaded yet, and I'm not sure if they also have to be reworked

**Comment by YamiVulgaris** [comment]
I would like to rework them, but for now we will just use the old one.

**Comment by YamiVulgaris** [comment]
@blueUserRed 
![image](https://github.com/blueUserRed/forty-five/assets/102359961/0d3cec7b-a78a-40b9-975a-ac5a6ca7cd1b)
